dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - $HOME/.mvn/

addons:
  apt:
    packages:
      - openjdk-6-jdk

before_install:
  - >
      export MVN_325=$HOME/.mvn/3.2.5
      which $MVN_325/bin/mvn || mkdir -p $MVN_325 &&
      curl https://apache.osuosl.org/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz |
      tar xz -C $MVN_325 --strip-components=1

matrix:
  allow_failures:
    - jdk: oraclejdk11
    - jdk: openjdk6
    - jdk: openjdk7
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
  include:
    #- jdk: oraclejdk7 #https://github.com/travis-ci/travis-ci/issues/7884
    - jdk: oraclejdk8
    - jdk: oraclejdk11
    - jdk: openjdk6
      env: PATH=$HOME/.mvn/3.2.5/bin:$PATH
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11


